// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kxqzzrzfibetusazksbg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt4cXp6cnpmaWJldHVzYXprc2JnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwMzc0NzAsImV4cCI6MjA2NDYxMzQ3MH0.bwlcN5EK0Iim8FRgJTmkfOMjNnIooJ6BS_8ZehBpnAM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);